# Generated by Django 2.2.4 on 2020-08-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20200816_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authors',
            new_name='books',
        ),
    ]
